Fix of animal spawn group
cbnolok/SphereX-Scriptpack pull request #54
Opened 2020-11-18 01:53 UTC by Jhobean

I fix the animal spawn group but I saw there some animal missing that I added 

c_sea_serpent_deep
c_wisp_dark
c_turkey
Any particular reason why you remove them?

I notice too there a missing file about custom sphere NPC
https://github.com/Sphereserver/Scripts/blob/0ebde261cd1db305ee202d736705247208a8f732/npcs/sphere_monsters_custom.scp#L1
It's normal?  lot of these NPC are in the script pack. I add the file or nuke all their apparition on script pack?

2020-11-19 02:28 UTC, Jhobean commented
I added All missing NPC that was on spawn group. I'm sure missing more npc again.

2020-11-22 18:56 UTC, cbnolok requested changes

2020-11-22 18:56 UTC, cbnolok commented on npcs/c_guards.scp
> -ON=@NPCRestock
What about moving the loot (gold) to @CreateLoot?

2020-11-22 18:56 UTC, cbnolok commented on npcs/c_monster_classic.scp
> +SUBSECTION=Aquatique
Is this the correct subsection?

2020-11-22 18:56 UTC, cbnolok commented on npcs/c_monster_classic.scp
> +SUBSECTION=Miscellaneous
What about starting to split monsters from the miscellaneous category, by adding some other categories, like magical or something like that, for this case?

2020-11-22 18:56 UTC, cbnolok commented on _syntax highlighting_incomplete/editplus/sphere.stx
> +c_black_crow
Since we are making a new script pack, we can use this occasion to discuss changes to the old namings... In this case, i'd see more appropriate c_bird_crow instead of c_black_crow, what do you think?

2020-11-22 18:56 UTC, cbnolok commented on npcs/c_citizens.scp
> +   ITEM=random_jewelry,1,R2
TODO (sooner or later, this isn't mandatory for the acceptance of your very good PR): move the citizens loot to @CreateLoot

2020-11-22 18:56 UTC, cbnolok commented on npcs/c_citizens.scp
> +   ITEM=random_jewelry,1,R2
Also, what about renaming those kind of script files to have a prefix like c_human_* ? To highlight that those aren't monsters but humanoids

2020-11-23 01:05 UTC, Jhobean commented on npcs/c_guards.scp
> -ON=@NPCRestock
Not there on final file

2020-11-23 01:06 UTC, Jhobean commented on _syntax highlighting_incomplete/editplus/sphere.stx
> +c_black_crow
Agree.. was c_bird_crow on 56d

2020-11-23 01:07 UTC, Jhobean commented on npcs/c_citizens.scp
> +   ITEM=random_jewelry,1,R2
Don't think it's loot on citizen it seem to be their "costume"

2020-11-23 01:09 UTC, Jhobean commented on npcs/c_monster_classic.scp
> +SUBSECTION=Aquatique
Was in french...

2020-11-23 01:18 UTC, Jhobean commented on npcs/c_monster_classic.scp
> +SUBSECTION=Miscellaneous
Change all subsection for NPC with  SUBSECTION=Miscellaneous

2020-11-30 22:27 UTC, merged