Add world generator and add/Fix some NPC
cbnolok/SphereX-Scriptpack pull request #88
Opened 2021-08-18 02:10 UTC by Jhobean

1- I added @Soulless-1 's world generator and fix #59 

![Uploading image.png…]()

2- Removed the Saves files folder (not need anymore)

3- Added some missing NPC and item

4- Add the Dungeons Chest by using Soulless Script (require for world spawning)

5- Added the files for manual Crop generation (People can decide to use them)

6- Added 20 OSI book template write one by one by soulless and implement the bookcase fill in the world generator

7- Started to remove some defs_heght after validating height is set in CHARDEF (Eventualy will remove all the defs_height)

2021-08-21 14:46 UTC, cbnolok requested changes

2021-08-21 14:46 UTC, cbnolok commented on items/i_deco_dungeons_traps_dead.scp
> +defname=memorialgwenn
Is that the correct defname?

2021-08-21 14:46 UTC, cbnolok commented on web/spherestatus.htm
> +update time 2021/08/13 00:11:24<br>
Was this file intended to be committed?

2021-08-21 17:42 UTC, Jhobean commented on web/spherestatus.htm
> +update time 2021/08/13 00:11:24<br>
No.  This file should be in the gitignore

2021-08-21 17:43 UTC, Jhobean commented on items/i_deco_dungeons_traps_dead.scp
> +defname=memorialgwenn
It was like this on an other script pack. Should be change its not the convention. Good see. Im out for the week end. Ill check monday or if you want you can fix it

2021-08-23 01:42 UTC, Jhobean commented
Should Be OK @cbnolok

2021-08-28 15:41 UTC, cbnolok requested changes

2021-08-28 15:41 UTC, cbnolok commented on crafting/crafting_events.scp
> +//<ACT>=l'item crafté
Could you translate in english?

2021-08-28 15:41 UTC, cbnolok commented on crafting/crafting_events.scp
> +if STRMATCH(*Tailoring*,<uid.<ref2>.SKILLMAKE.1.key>) && STRMATCH(*i_cloth*,<serv.itemdef.<ref2.baseid>.resources>)
Internally defnames (skills, items...) are converted to fixed a numerical value. Could you use the == operator to do the checks? Using string comparison when you could just use numerical comparison is bad practice and we shouldn't have that on default scriptpack

2021-08-28 15:41 UTC, cbnolok commented on functions/f_dungeon_chest.scp
> +if (!<isevent.t_container_locked>) && (!<isevent.t_container>) && (!<type>==t_container_locked) && (!<type>==t_container)
Can you directly use != operator?

2021-09-04 09:15 UTC, merged